Repository fabric8-ui/fabric8-planner, pull requests merged in 2018-02, with the labels that each got.

#2439 fix(build): encapsulate TS transpiling to work with watch mode
  gulpfile.js
Labels: Ready for review, bug fixed

#2440 fix(tree/flat-list): bug fixes in flat-list and tree-view
  src/app/components/planner-list/planner-list.component.ts
Labels: Ready for review

#2452 fix(tests): Fix incorrect karma config file path
  runtime/package.json
Labels: Ready for review

#2453 fix(tests): Remove extra karma config file
  runtime/config/karma.config.js
Labels: Ready for review

#2419 Externalized Black Box Test Runner
  .gitignore
  deploy/release.groovy
  docs/testing.adoc
  package-lock.json
  runtime/package-lock.json
  runtime/src/tests/functionalTests/run_ts_functional_tests.sh
  runtime/src/tests/functionalTests/scripts/common.inc.sh
  runtime/src/tests/functionalTests/scripts/lib/core.inc.sh
  runtime/src/tests/functionalTests/scripts/lib/logger.inc.sh
  runtime/src/tests/functionalTests/tsconfig.json
  runtime/tests/docker-entrypoint.sh
  runtime/tests/lib/common.inc.sh
  runtime/tests/run_js_functional_tests.sh
  runtime/tests/upload_to_codecov.sh
  scripts/run-functests.sh
  src/tests/mixins/index.ts
  src/tests/mixins/logging.ts
  src/tests/page_objects/app.page.ts
  src/tests/page_objects/base.page.ts
  src/tests/page_objects/index.ts
  src/tests/page_objects/planner/index.ts
  src/tests/page_objects/planner/planner.page.ts
  src/tests/specs/smokeTest.spec.ts
  src/tests/support/constants.ts
  src/tests/support/core.ts
  src/tests/support/index.ts
  src/tests/tsconfig.json
  src/tests/ui/base.element.ts
  src/tests/ui/button.ts
  src/tests/ui/checkbox.ts
  src/tests/ui/dropdown.ts
  src/tests/ui/index.ts
  src/tests/ui/modal_dialog.ts
  src/tests/ui/multi_select_list.ts
  src/tests/ui/planner/index.ts
  src/tests/ui/planner/sidepanel.ts
  src/tests/ui/planner/workitem-list-entry.ts
  src/tests/ui/planner/workitem-list.ts
  src/tests/ui/planner/workitem-quickadd.ts
  src/tests/ui/planner/workitem-quickpreview.ts
  src/tests/ui/text_input.ts
  tests/README.adoc
  tests/package.json
  tests/protractor.conf.ts
  tests/run.sh
  tests/tsconfig.json
Labels: Ready for review

#2479 fix(table-version): table version is fixed to 11.2.3
  package.json
Labels: important

#2441 fix(test): Fix the filter drop down
  src/app/components/group-types-panel/group-types-panel.component.ts
  src/app/components/planner-list/planner-list.component.ts
  src/app/mock/mock-data.service.ts
  src/app/mock/mock-data/filter-mock-generator.ts
  src/app/mock/mock-data/work-item-mock-generator.ts
  src/app/mock/mock-http.ts
Labels: Ready for review
